"""Backtesting: fees/slippage-aware, walk-forward split validation, and a
fuller set of risk-adjusted metrics than a single total-return number.

Every signal is generated by calling the strategy's actual generate_signals()
at each historical point, using only data available up to that point (no
lookahead) — this exercises the exact same code path the live bot runs, not
a separate re-implementation that could silently diverge from it. That's the
main rigor property here: the backtest can't lie about what the strategy
would really have done.

Walk-forward splitting is the other piece: rather than one big number over
one (lucky or unlucky) historical window, the data is split into several
sequential periods and each is backtested independently, so an edge that
only existed in one stretch of history is visible as inconsistency across
windows rather than hidden inside a single blended average.
"""

import pandas as pd

from .data import fetch_history, fetch_intraday
from .indicators import atr as compute_atr
from .strategy import (
    EnsembleVote,
    MeanReversionPullback,
    OpeningRangeConfluence,
    SMACrossover,
    Signal,
    VWAPReclaim,
)

TRADING_DAYS_PER_YEAR = 252
# Trading212 charges no commission on stock trades; the real cost is the
# bid-ask spread / market-order slippage, not a fee. slippage_bps applies on
# both entry and exit (a round trip pays it twice), fee_bps defaults to 0
# accordingly but is still overridable for other brokers/instruments.
DEFAULT_FEE_BPS = 0.0
DEFAULT_SLIPPAGE_BPS = 5.0


def _signal_series(strategy, df: pd.DataFrame, min_bars: int,
                    confirm_df: pd.DataFrame | None = None) -> pd.Series:
    """confirm_df (optional): a finer-grained bar series for the same symbol,
    sliced up to each step's current timestamp (no lookahead) and passed as
    the strategy's confirm_prices -- see OpeningRangeConfluence.confirm_bars.

    Returns the full SignalResult per step (not just .signal), so callers
    can inspect .reason -- e.g. EnsembleVote tags a BUY's reason with which
    sub-strategies agreed, letting _build_trades attach that to the trade."""
    signals = []
    for i in range(min_bars, len(df) + 1):
        prices = {"X": df.iloc[:i]}
        confirm_prices = None
        if confirm_df is not None:
            confirm_prices = {"X": confirm_df[confirm_df.index <= df.index[i - 1]]}
        signals.append(strategy.generate_signals(prices, confirm_prices)["X"])
    return pd.Series(signals, index=df.index[min_bars - 1:])


def _build_trades(df: pd.DataFrame, signal_results: pd.Series, fee_bps: float, slippage_bps: float,
                   stop_atr_multiple: float | None = None, atr_series: pd.Series | None = None,
                   stop_loss_pct: float | None = None, take_profit_pct: float | None = None) -> list:
    """stop_atr_multiple (optional): force-close a position the first day its bar Low
    touches entry_price - stop_atr_multiple * (ATR at entry), regardless of what the
    strategy's own signal says that day — models a real stop order sitting with the
    broker. Off by default (None), matching the current live bot's behavior, which
    sizes positions as if this stop exists (see RiskManager.size_buy) but never
    actually places one.

    stop_loss_pct / take_profit_pct (optional): fixed-percentage alternative to the
    ATR stop — exit the first bar whose Low touches entry_price * (1 - stop_loss_pct)
    or whose High touches entry_price * (1 + take_profit_pct). If both stops (ATR and
    fixed-pct) are active, the tighter (higher) stop price wins. If a single bar's
    range spans both the stop and the target, the stop is assumed to hit first (the
    conservative, can't-know-intrabar-order assumption also used for the ATR stop).

    Each trade records entry_reason -- the entry signal's .reason (e.g. an
    EnsembleVote's voting-strategy breakdown), None for strategies that
    don't set one."""
    cost_frac = (fee_bps + slippage_bps) / 10000.0
    trades = []
    position = None
    for date, sig_result in signal_results.items():
        sig = sig_result.signal
        row = df.loc[date]
        price = float(row["Close"])

        if position is not None and position.get("stop_price") is not None:
            if float(row["Low"]) <= position["stop_price"]:
                exit_price = position["stop_price"] * (1 - cost_frac)
                trades.append({
                    "entry_date": position["entry_date"], "exit_date": date,
                    "entry_price": position["entry_price"], "exit_price": exit_price,
                    "pnl_pct": exit_price / position["entry_price"] - 1,
                    "open_at_end": False, "exit_reason": "stop_loss",
                    "entry_reason": position.get("entry_reason"),
                })
                position = None
                continue

        if position is not None and position.get("target_price") is not None:
            if float(row["High"]) >= position["target_price"]:
                exit_price = position["target_price"] * (1 - cost_frac)
                trades.append({
                    "entry_date": position["entry_date"], "exit_date": date,
                    "entry_price": position["entry_price"], "exit_price": exit_price,
                    "pnl_pct": exit_price / position["entry_price"] - 1,
                    "open_at_end": False, "exit_reason": "take_profit",
                    "entry_reason": position.get("entry_reason"),
                })
                position = None
                continue

        if position is None and sig is Signal.BUY:
            entry_price = price * (1 + cost_frac)
            stop_price = None
            if stop_atr_multiple and atr_series is not None:
                a = atr_series.get(date)
                if a and a > 0:
                    # Floored just above zero: an abnormally large ATR (e.g. a data-quality
                    # spike around a split/dividend adjustment) could otherwise push the
                    # computed stop below zero, which is not a real order price and would
                    # corrupt the equity curve (negative equity -> nan CAGR downstream).
                    stop_price = max(price - stop_atr_multiple * a, price * 0.001)
            if stop_loss_pct is not None:
                pct_stop = price * (1 - stop_loss_pct)
                stop_price = max(stop_price, pct_stop) if stop_price is not None else pct_stop
            target_price = price * (1 + take_profit_pct) if take_profit_pct is not None else None
            position = {"entry_date": date, "entry_price": entry_price,
                        "stop_price": stop_price, "target_price": target_price,
                        "entry_reason": sig_result.reason}
        elif position is not None and sig is Signal.SELL:
            exit_price = price * (1 - cost_frac)
            trades.append({
                "entry_date": position["entry_date"], "exit_date": date,
                "entry_price": position["entry_price"], "exit_price": exit_price,
                "pnl_pct": exit_price / position["entry_price"] - 1,
                "open_at_end": False, "exit_reason": "signal",
                "entry_reason": position.get("entry_reason"),
            })
            position = None
    if position is not None:
        last_date = signal_results.index[-1]
        exit_price = float(df.loc[last_date, "Close"]) * (1 - cost_frac)
        trades.append({
            "entry_date": position["entry_date"], "exit_date": last_date,
            "entry_price": position["entry_price"], "exit_price": exit_price,
            "pnl_pct": exit_price / position["entry_price"] - 1,
            "open_at_end": True, "exit_reason": "end_of_data",
            "entry_reason": position.get("entry_reason"),
        })
    return trades


def _equity_curve(dates, df: pd.DataFrame, trades: list) -> pd.Series:
    equity, idx = [], []
    cash_equity = 1.0
    trade_iter = iter(trades)
    current = next(trade_iter, None)
    base = None
    for date in dates:
        price = float(df.loc[date, "Close"])
        if current and current["entry_date"] <= date <= current["exit_date"]:
            if base is None:
                base = cash_equity
            if date == current["exit_date"]:
                cash_equity = base * (current["exit_price"] / current["entry_price"])
                equity.append(cash_equity)
                base = None
                current = next(trade_iter, None)
            else:
                equity.append(base * (price / current["entry_price"]))
        else:
            equity.append(cash_equity)
        idx.append(date)
    return pd.Series(equity, index=idx)


def simulate(strategy, df: pd.DataFrame, fee_bps: float = DEFAULT_FEE_BPS,
             slippage_bps: float = DEFAULT_SLIPPAGE_BPS, min_bars: int = 60,
             stop_atr_multiple: float | None = None, atr_period: int = 14,
             confirm_df: pd.DataFrame | None = None,
             stop_loss_pct: float | None = None, take_profit_pct: float | None = None):
    """Long-only, single position at a time, all-in/all-out, cost-aware.

    Returns (equity_curve, trades). Not enough data -> a flat 1-bar curve
    and no trades, rather than raising, so a thin window in walk-forward
    just reports as empty instead of blowing up the whole run.
    """
    if len(df) <= min_bars:
        return pd.Series([1.0], index=df.index[-1:]), []
    signals = _signal_series(strategy, df, min_bars, confirm_df)
    atr_series = compute_atr(df, period=atr_period) if stop_atr_multiple else None
    trades = _build_trades(df, signals, fee_bps, slippage_bps, stop_atr_multiple, atr_series,
                            stop_loss_pct, take_profit_pct)
    equity = _equity_curve(signals.index, df, trades)
    return equity, trades


def compute_metrics(equity: pd.Series, trades: list, periods_per_year: int = TRADING_DAYS_PER_YEAR) -> dict:
    if len(equity) < 2:
        return {}
    daily_ret = equity.pct_change().dropna()
    years = len(equity) / periods_per_year
    total_return = equity.iloc[-1] / equity.iloc[0] - 1
    cagr = (equity.iloc[-1] / equity.iloc[0]) ** (1 / years) - 1 if years > 0 and equity.iloc[0] > 0 else 0.0
    vol = daily_ret.std() * (periods_per_year ** 0.5)
    sharpe = (daily_ret.mean() * periods_per_year) / vol if vol > 0 else 0.0
    downside = daily_ret[daily_ret < 0]
    downside_vol = downside.std() * (periods_per_year ** 0.5) if len(downside) > 1 else 0.0
    sortino = (daily_ret.mean() * periods_per_year) / downside_vol if downside_vol > 0 else 0.0
    drawdown = equity / equity.cummax() - 1

    closed = [t for t in trades if not t.get("open_at_end")]
    wins = [t for t in closed if t["pnl_pct"] > 0]
    losses = [t for t in closed if t["pnl_pct"] <= 0]
    win_rate = len(wins) / len(closed) if closed else 0.0
    avg_win = sum(t["pnl_pct"] for t in wins) / len(wins) if wins else 0.0
    avg_loss = sum(t["pnl_pct"] for t in losses) / len(losses) if losses else 0.0
    gross_win = sum(t["pnl_pct"] for t in wins)
    gross_loss = abs(sum(t["pnl_pct"] for t in losses))
    profit_factor = (gross_win / gross_loss) if gross_loss > 0 else (float("inf") if gross_win > 0 else 0.0)

    max_consec_losses = streak = 0
    for t in closed:
        if t["pnl_pct"] <= 0:
            streak += 1
            max_consec_losses = max(max_consec_losses, streak)
        else:
            streak = 0
    stopped_out = sum(1 for t in closed if t.get("exit_reason") == "stop_loss")
    took_profit = sum(1 for t in closed if t.get("exit_reason") == "take_profit")

    return {
        "total_return": total_return,
        "cagr": cagr,
        "sharpe": sharpe,
        "sortino": sortino,
        "max_drawdown": drawdown.min(),
        "num_trades": len(trades),
        "closed_trades": len(closed),
        "win_rate": win_rate,
        "avg_win": avg_win,
        "avg_loss": avg_loss,
        "profit_factor": profit_factor,
        "max_consecutive_losses": max_consec_losses,
        "stopped_out": stopped_out,
        "took_profit": took_profit,
        "trades": trades,
    }


def walk_forward(strategy_factory, df: pd.DataFrame, n_windows: int = 4,
                  fee_bps: float = DEFAULT_FEE_BPS, slippage_bps: float = DEFAULT_SLIPPAGE_BPS,
                  min_bars: int = 60, periods_per_year: int = TRADING_DAYS_PER_YEAR,
                  stop_atr_multiple: float | None = None, atr_period: int = 14,
                  confirm_df: pd.DataFrame | None = None,
                  stop_loss_pct: float | None = None, take_profit_pct: float | None = None) -> list:
    """Split df into n_windows sequential, non-overlapping chunks and backtest
    each independently with a fresh strategy instance.

    Each window resets the strategy's indicator warmup at its own start —
    a documented simplification, not a seamless continuous backtest. The
    point is comparing independent periods for consistency, not precision at
    the window seam.

    confirm_df (optional): sliced to each window's date range and passed
    through to simulate() -- see _signal_series.
    """
    n = len(df)
    if n_windows < 1:
        raise ValueError("n_windows must be >= 1")
    size = n // n_windows
    if size <= min_bars:
        raise ValueError(
            f"Not enough data for {n_windows} windows of at least {min_bars} bars each "
            f"({n} bars total) — use fewer windows or a longer period."
        )

    rows = []
    for i in range(n_windows):
        start = i * size
        end = n if i == n_windows - 1 else (i + 1) * size
        window_df = df.iloc[start:end]
        window_confirm_df = None
        if confirm_df is not None:
            window_confirm_df = confirm_df[(confirm_df.index >= window_df.index[0])
                                            & (confirm_df.index <= window_df.index[-1])]
        equity, trades = simulate(strategy_factory(), window_df, fee_bps, slippage_bps, min_bars,
                                   stop_atr_multiple, atr_period, confirm_df=window_confirm_df,
                                   stop_loss_pct=stop_loss_pct, take_profit_pct=take_profit_pct)
        metrics = compute_metrics(equity, trades, periods_per_year)
        metrics["window"] = i + 1
        metrics["start"] = window_df.index[0]
        metrics["end"] = window_df.index[-1]
        rows.append(metrics)
    return rows


def _pct(x) -> str:
    return f"{x:+.1%}" if isinstance(x, (int, float)) else "n/a"


def print_backtest(symbols: list, fast: int = 20, slow: int = 50, n_windows: int = 4,
                    fee_bps: float = DEFAULT_FEE_BPS, slippage_bps: float = DEFAULT_SLIPPAGE_BPS,
                    period: str = "5y", stop_atr_multiple: float | None = None,
                    trend_filter: int | None = None) -> None:
    print(f"Swing strategy: SMA({fast}/{slow}) crossover, {period} daily bars, long-only.")
    if trend_filter:
        print(f"Trend filter: BUY only when price is above its {trend_filter}-day SMA.")
    if stop_atr_multiple:
        print(f"Stop-loss: {stop_atr_multiple}x ATR(14) below entry, checked against each bar's Low.")
    print(f"Costs modeled: {fee_bps:.0f} bps fee + {slippage_bps:.0f} bps slippage per side "
          f"(Trading212 charges no stock commission; this approximates spread/slippage).")
    print(f"Walk-forward: {n_windows} sequential out-of-sample windows per symbol.\n")

    price_data = fetch_history(symbols, period=period)
    if not price_data:
        print("No data for any symbol.")
        return

    for sym, df in price_data.items():
        try:
            windows = walk_forward(lambda: SMACrossover(fast, slow, trend_filter), df, n_windows,
                                    fee_bps, slippage_bps, stop_atr_multiple=stop_atr_multiple)
        except ValueError as exc:
            print(f"{sym}: {exc}")
            continue

        print(f"=== {sym} ===")
        header = f"{'window':>6} {'period':<23} {'CAGR':>8} {'Sharpe':>7} {'MaxDD':>8} {'WinRate':>8} {'Trades':>7}"
        print(header)
        for w in windows:
            if not w:
                continue
            span = f"{w['start'].date()} to {w['end'].date()}"
            print(f"{w['window']:>6} {span:<23} {_pct(w['cagr']):>8} {w['sharpe']:>7.2f} "
                  f"{_pct(w['max_drawdown']):>8} {_pct(w['win_rate']):>8} {w['closed_trades']:>7}")

        positive_windows = sum(1 for w in windows if w and w["total_return"] > 0)
        valid_windows = sum(1 for w in windows if w)
        print(f"  -> profitable in {positive_windows}/{valid_windows} windows "
              f"(consistency, not just a single blended average)\n")


def print_daytrade_backtest(symbols: list, alpaca_api_key: str, alpaca_api_secret: str,
                             or_minutes: int = 30, n_windows: int = 2,
                             fee_bps: float = DEFAULT_FEE_BPS, slippage_bps: float = DEFAULT_SLIPPAGE_BPS,
                             confirm_bars: int = 3,
                             stop_loss_pct: float | None = None, take_profit_pct: float | None = None,
                             rsi_buy_range: tuple[float, float] | None = None,
                             min_ema_spread_pct: float | None = None,
                             min_strength: float | None = None,
                             min_volume_ratio: float | None = None,
                             require_retest: bool = False,
                             retest_tolerance_pct: float = 0.003,
                             strategy_name: str = "orb",
                             ensemble_min_votes: int | None = None) -> None:
    """Backtests a day-trade strategy on intraday bars. Always backtests the
    primary signal on 5-minute bars regardless of the live bot's
    DAYTRADE_BAR_MINUTES setting -- fewer, steadier bars keep this a quick
    sanity check rather than a slow pull of tens of thousands of bars per
    symbol.

    strategy_name: "orb" (default) is OpeningRangeConfluence -- all the
    params below except stop_loss_pct/take_profit_pct only apply to it.
    "mean_reversion" is MeanReversionPullback, tested with its own code
    defaults for now (no CLI knobs yet). "ensemble" is EnsembleVote wrapping
    all three of OpeningRangeConfluence + MeanReversionPullback + VWAPReclaim
    (each at its own code defaults, orb with confirm_bars=0 since no
    1-minute data is fetched for this mode) -- requires ensemble_min_votes of
    the three to agree before a BUY fires (None = unanimous, all three; a
    3-strategy unanimous vote turned out to produce only 11 trades across a
    60-day/30-symbol backtest, too few to draw any conclusion from -- try
    ensemble_min_votes=2 for a majority instead). confirm_bars/rsi_buy_range/
    min_ema_spread_pct/min_strength/min_volume_ratio/require_retest are
    silently ignored outside "orb" mode since none of them apply to the
    other strategies.

    confirm_bars > 0 (orb only) additionally pulls 1-minute bars and
    exercises the same confirm_bars entry gate the live bot uses (see
    OpeningRangeConfluence) -- the whole point being to compare against a
    confirm_bars=0 run before trusting the gate live.

    stop_loss_pct / take_profit_pct (optional, any strategy_name): fixed-
    percentage exits checked against each bar's Low/High -- see
    _build_trades. None of these strategies place either order live today;
    for orb, see run_day_trade_cycle.

    rsi_buy_range / min_ema_spread_pct / min_strength / min_volume_ratio
    (optional, orb only): entry-side experiments -- see
    OpeningRangeConfluence. None uses the strategy's own defaults (no gate).

    require_retest / retest_tolerance_pct (orb only): replaces the entry
    trigger itself with a pullback-and-hold retest of the opening-range high
    instead of buying the first breakout bar -- see OpeningRangeConfluence."""
    if strategy_name == "mean_reversion":
        header = ["Day-trade strategy: mean-reversion pullback + EMA/RSI confluence, 5-min bars"]
    elif strategy_name == "ensemble":
        votes_desc = "all 3 must agree" if not ensemble_min_votes or ensemble_min_votes >= 3 \
            else f"{ensemble_min_votes} of 3 must agree"
        header = ["Day-trade strategy: ensemble vote (opening-range breakout + "
                   f"mean-reversion pullback + VWAP reclaim, {votes_desc}), 5-min bars"]
    else:
        header = ["Day-trade strategy: opening-range breakout"
                  + (" + retest" if require_retest else "") + " + EMA/RSI confluence, 5-min bars"]
        if confirm_bars:
            header.append(f"{confirm_bars}-bar 1-min confirmation")
        if rsi_buy_range:
            header.append(f"RSI buy band {rsi_buy_range[0]:.0f}-{rsi_buy_range[1]:.0f}")
        if min_ema_spread_pct:
            header.append(f"min EMA spread {min_ema_spread_pct:.2%}")
        if min_strength:
            header.append(f"min strength {min_strength:.2f}")
        if min_volume_ratio:
            header.append(f"min volume ratio {min_volume_ratio:.2f}x")
        if require_retest:
            header.append(f"retest tolerance {retest_tolerance_pct:.2%}")
    if stop_loss_pct or take_profit_pct:
        sl = f"{stop_loss_pct:.1%} stop-loss" if stop_loss_pct else "no stop-loss"
        tp = f"{take_profit_pct:.1%} take-profit" if take_profit_pct else "no take-profit"
        header.append(f"{sl} / {tp}")
    print(", ".join(header) + ".")
    print(f"Costs modeled: {fee_bps:.0f} bps fee + {slippage_bps:.0f} bps slippage per side.")
    print("Note: this pulls 60 days of 5-minute history from Alpaca -- a recent-behavior "
          "sanity check, not a long-run edge validation.\n")

    price_data = fetch_intraday(symbols, alpaca_api_key, alpaca_api_secret, days=60, timeframe="5Min")
    if not price_data:
        print("No intraday data for any symbol.")
        return

    confirm_data = {}
    if confirm_bars and strategy_name == "orb":
        confirm_data = fetch_intraday(list(price_data.keys()), alpaca_api_key, alpaca_api_secret,
                                       days=60, timeframe="1Min")

    def strategy_factory():
        if strategy_name == "mean_reversion":
            return MeanReversionPullback()
        if strategy_name == "ensemble":
            return EnsembleVote([
                OpeningRangeConfluence(or_minutes=or_minutes, confirm_bars=0),
                MeanReversionPullback(),
                VWAPReclaim(),
            ], min_votes=ensemble_min_votes)
        return OpeningRangeConfluence(
            or_minutes=or_minutes, confirm_bars=confirm_bars,
            rsi_buy_range=rsi_buy_range or (50, 70), min_ema_spread_pct=min_ema_spread_pct,
            min_strength=min_strength, min_volume_ratio=min_volume_ratio,
            require_retest=require_retest, retest_tolerance_pct=retest_tolerance_pct)

    vote_breakdown = {}  # entry_reason -> {"trades": int, "wins": int, "pnl_sum": float}

    bars_per_day = 78  # ~6.5h US session / 5-min bars
    for sym, df in price_data.items():
        try:
            windows = walk_forward(
                strategy_factory,
                df, n_windows, fee_bps, slippage_bps, min_bars=bars_per_day,
                periods_per_year=TRADING_DAYS_PER_YEAR * bars_per_day,
                confirm_df=confirm_data.get(sym),
                stop_loss_pct=stop_loss_pct, take_profit_pct=take_profit_pct)
        except ValueError as exc:
            print(f"{sym}: {exc}")
            continue

        print(f"=== {sym} ===")
        for w in windows:
            if not w:
                continue
            span = f"{w['start'].date()} to {w['end'].date()}"
            print(f"  window {w['window']} ({span}): total return {_pct(w['total_return'])}, "
                  f"win rate {_pct(w['win_rate'])}, {w['closed_trades']} trades, "
                  f"avg win {_pct(w['avg_win'])}, avg loss {_pct(w['avg_loss'])}, "
                  f"max drawdown {_pct(w['max_drawdown'])}")
            if strategy_name == "ensemble":
                for t in w["trades"]:
                    if t.get("open_at_end"):
                        continue
                    key = t.get("entry_reason") or "unknown"
                    bucket = vote_breakdown.setdefault(key, {"trades": 0, "wins": 0, "pnl_sum": 0.0})
                    bucket["trades"] += 1
                    bucket["wins"] += 1 if t["pnl_pct"] > 0 else 0
                    bucket["pnl_sum"] += t["pnl_pct"]
        print()

    if strategy_name == "ensemble" and vote_breakdown:
        print("=== Vote-composition breakdown (which strategies agreed) ===")
        for key, b in sorted(vote_breakdown.items(), key=lambda kv: -kv[1]["trades"]):
            win_rate = b["wins"] / b["trades"] if b["trades"] else 0.0
            avg_pnl = b["pnl_sum"] / b["trades"] if b["trades"] else 0.0
            print(f"  {key}: {b['trades']} trades, win rate {win_rate:+.1%}, avg pnl/trade {avg_pnl:+.2%}")
        print()
